server:
  port: 8091

#PostgreSQL DS configs
spring:
  datasource:
    url: ${SONG_POSTGRES_JDBC_URL}
    driver-class-name: org.postgresql.Driver
    username: ${SONG_POSTGRES_USER}
    password: ${SONG_POSTGRES_PASSWORD}

  sql:
    init:
      mode:
        always

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none

logging:
  level:
    com.ms.base.ss: DEBUG

eureka:
  client:
    serviceUrl:
      defaultZone: http://host.docker.internal:8761/eureka
    registerWithEureka: true
    fetchRegistry: true